In [1]:
import pandas
import numpy as np
from OneHotEncoder import OHE

Xtrain = pandas.DataFrame({'Sex':['M','F','M','M','F','NA','NA','NA','F','M'],'cat':['P','P','af','P','CD','P','CD','G','P','Q']})
print(Xtrain)

  Sex cat
0   M   P
1   F   P
2   M  af
3   M   P
4   F  CD
5  NA   P
6  NA  CD
7  NA   G
8   F   P
9   M   Q


In [2]:
print('Train encoder and transform the data frame; Transformed dataframe:')
enc = OHE(Xtrain, ref=['F', 'CD'])
A = enc.transform(Xtrain)
print(A)

Train encoder and transform the data frame; Transformed dataframe:
[[0. 1. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 1.]
 [0. 1. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 1. 0.]
 [1. 0. 0. 0. 0. 0.]
 [1. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 1. 0. 0.]]


In [3]:
print('Reverse transform back to the data frame; Reverse transformed array:')
retransform = enc.rev_transform(A)
print(retransform)
print('Identical elements:')
print(retransform==Xtrain)

Reverse transform back to the data frame; Reverse transformed array:
  Sex cat
0   M   P
1   F   P
2   M  af
3   M   P
4   F  CD
5  NA   P
6  NA  CD
7  NA   G
8   F   P
9   M   Q
Identical elements:
    Sex   cat
0  True  True
1  True  True
2  True  True
3  True  True
4  True  True
5  True  True
6  True  True
7  True  True
8  True  True
9  True  True
